### ISSUE TITLE
CUSTOM MODEL DATA ERROR

### ISSUE THREAD

**Issue by NessunoMC** [relavis/VehiclesPlus#33]
Using the custom model data in the vehicle.yml, when I try to buy the vehicle from the shop it give this error.

`[16:03:35 WARN]: [VehiclesPlusPro] Task #37024 for VehiclesPlusPro v2.0.8 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.LeatherArmorMeta
        at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand$2$1.run(VehiclesCommand.java:274) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

This is the vehicles.yml

partList:
  list0:
    className: me.legofreak107.vehiclesplus.vehicles.vehicles.objects.addons.skins.Skin
    skin:
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: STICK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        Unbreakable: true
        custom-model-data: 1000

**Comment by relavis** [comment]
Follow the issue format
