### ISSUE TITLE
Error message I cant do any commands

### ISSUE THREAD

**Issue by zefyelol** [relavis/VehiclesPlus#40]
I dont have any coding knowledge I have pro im using Xeconomy 
console
Error occurred while enabling VehiclesPlusPro v2.0.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at me.legofreak107.vehiclesplus.VehiclesPlus.onEnable(VehiclesPlus.java:121) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:448) [craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:374) [craftbukkit.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:448) [craftbukkit.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:254) [craftbukkit.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:762) [craftbukkit.jar:git-Bukkit-8160e29]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[craftbukkit.jar:git-Bukkit-8160e29]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        ... 10 more

**Comment by relavis** [comment]
Please follow the issue format.

**Comment by relavis** [comment]
Continued on #42
