### ISSUE TITLE
I downloaded the plugin last night but I cannot use it (repost with correct format)

### ISSUE THREAD

**Issue by zefyelol** [relavis/VehiclesPlus#42]
**Describe the bug**  
I downloaded the plugin last night but when I try to use it it says error possibly not up to date

**To Reproduce**  
1. Start my server using a bat file
2. wait for it to start
3. Scroll to see if its working

**Expected behavior**  
I expect it to not say that error, and for me to be able to use the plugin on my server.

**Screenshots or Video Recordings**  
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Information**  
 - Installed plugins:timber, sleep better, factions, xeconomy, vault, protocallib
 - VehiclesPlus Version: 2.0.9
 - Pro or Lite? pro
 - Server Platform and Version PaperSpigot 1.15.2 #385
 - Operating System (if applicable):windows ten

Console:
Error occurred while enabling VehiclesPlusPro v2.0.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
at me.legofreak107.vehiclesplus.VehiclesPlus.onEnable(VehiclesPlus.java:121) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Bukkit-8160e29]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit.jar:git-Bukkit-8160e29]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit.jar:git-Bukkit-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:448) [craftbukkit.jar:git-Bukkit-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:374) [craftbukkit.jar:git-Bukkit-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:448) [craftbukkit.jar:git-Bukkit-8160e29]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:254) [craftbukkit.jar:git-Bukkit-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:762) [craftbukkit.jar:git-Bukkit-8160e29]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[craftbukkit.jar:git-Bukkit-8160e29]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[craftbukkit.jar:git-Bukkit-8160e29]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
... 10 more

**Comment by zefyelol** [comment]
@relavis any idea on the issue? Ive tried different eco plugins and different versions of the plugin.

**Comment by relavis** [comment]
Redownload Paper from papermc.io. Don't be downloading it from shady websites.
