### ISSUE TITLE
Player gets kicked out of car

### ISSUE THREAD

**Issue by stijnb1234** [relavis/VehiclesPlus#48]
**Describe the bug**  
The player gets kicked out of the car randomly.

**To Reproduce**  
1. Drive around.
2. Get kicked out of your car

**Expected behavior**  
It should not happen.

**Screenshots or Video Recordings**  
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Information**  
PaperSpigot 1.12.2, devbuild of VehiclesPlusPro

**Additional context**  
The error I get:
```
[19:54:10 WARN]: Entity threw exception at Mugello:-448.7401123046875,2.6,1592.98876953125
[19:54:10 WARN]: java.util.NoSuchElementException
[19:54:10 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.UnsafeList$Itr.next(UnsafeList.java:248)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:1015)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.World.getEntities(World.java:2630)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.EntityArmorStand.cB(EntityArmorStand.java:315)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2199)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:2024)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.EntityArmorStand.B_(EntityArmorStand.java:579)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1767)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:54:10 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:54:10 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by stijnb1234** [comment]
Found this issue:
https://github.com/konsolas/AAC-Issues/issues/551

**Comment by relavis** [comment]
Should be fixed
